apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: retail-promotion-platform
type: Opaque
stringData:
  password: retail_pass

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: retail-promotion-platform
data:
  init.sql: |
    CREATE DATABASE security_db;
    CREATE DATABASE promotion_command_db;
    CREATE DATABASE product_db;
    CREATE DATABASE inventory_db;
    CREATE DATABASE pricing_db;
    CREATE DATABASE order_db;
    CREATE DATABASE notification_db;
    CREATE DATABASE audit_db;

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: retail-promotion-platform
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: retail-promotion-platform

spec:
  serviceName: postgres
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:

    metadata:
      labels:
        app: postgres

    spec:

      containers:

        - name: postgres

          image: postgres:16-alpine

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5432

          env:

            - name: POSTGRES_USER
              value: retail_admin

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password

            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          volumeMounts:

            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d

          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 40
            periodSeconds: 20

      volumes:

        - name: postgres-init
          configMap:
            name: postgres-init

  volumeClaimTemplates:

    - metadata:
        name: postgres-storage

      spec:

        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 10Gi