apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: retail-promotion-platform
data:
  init.sql: |
    CREATE DATABASE security_db;
    CREATE DATABASE promotion_command_db;
    CREATE DATABASE product_db;
    CREATE DATABASE inventory_db;
    CREATE DATABASE pricing_db;
    CREATE DATABASE order_db;
    CREATE DATABASE notification_db;
    CREATE DATABASE audit_db;

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: retail-promotion-platform
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: retail-promotion-platform

spec:
  serviceName: postgres
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_USER
              value: retail_admin

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: retail-platform-secrets
                  key: POSTGRES_PASSWORD

            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          volumeMounts:
            # Persistent PostgreSQL database files
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

            # SQL initialization script from ConfigMap
            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d

            # Azure Key Vault secrets mounted as files
            - name: secrets-store-inline
              mountPath: /mnt/secrets-store
              readOnly: true

          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 40
            periodSeconds: 20

      volumes:
        # Provides init.sql from the ConfigMap
        - name: postgres-init
          configMap:
            name: postgres-init

        # Connects this pod to the SecretProviderClass
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-keyvault

  volumeClaimTemplates:
    - metadata:
        name: postgres-storage

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 10Gi