apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: azure-keyvault
  namespace: retail-promotion-platform

spec:
  provider: azure

  secretObjects:
    - secretName: retail-platform-secrets
      type: Opaque
      data:
        - objectName: postgres-password
          key: POSTGRES_PASSWORD

        - objectName: grafana-admin-password
          key: GRAFANA_ADMIN_PASSWORD

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"

    # Client ID of the AKS Key Vault CSI add-on identity
    userAssignedIdentityID: "6168766c-c542-4a82-b901-9815ddcfd728"

    keyvaultName: "retail-platform-kv"

    tenantId: "d66bb39e-9bf5-4f6d-be83-cad47bfbbbc3"

    objects: |
      array:
        - |
          objectName: postgres-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: grafana-admin-password
          objectType: secret
          objectVersion: ""