apiVersion: apps/v1
kind: Deployment
metadata:
  name: promotion-query-service
  namespace: retail-promotion-platform
  labels:
    app: promotion-query-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promotion-query-service
  template:
    metadata:
      labels:
        app: promotion-query-service
    spec:
      containers:
        - name: promotion-query-service
          image: retailplatformacr.azurecr.io/promotion-query-service:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://discovery-server:8761/eureka/"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-server:8888"
          resources:
            requests:
              cpu: "250m"
              memory: "384Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8083
            initialDelaySeconds: 45
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: promotion-query-service
  namespace: retail-promotion-platform
spec:
  selector:
    app: promotion-query-service
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP
